In [2]:
from google.colab import files
upload=files.upload()

Saving Iris.csv to Iris.csv


In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
df=pd.read_csv('Iris.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,ConfusionMatrixDisplay

In [5]:
df.drop(['Id'],inplace=True,axis=1)
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
x=df.drop(['Species'],axis=1)
y=df['Species']


In [10]:
scaler = StandardScaler()
x=scaler.fit_transform(x)
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
accuracies=[]
k_values=range(1,21)
for k in k_values:
  KNN=KNeighborsClassifier(n_neighbors=k)
  KNN.fit(x_train,y_train)
  y_pred=KNN.predict(x_test)
  acc=accuracy_score(y_test,y_pred)
  accuracies.append(acc)
  print(f'Accuracy for k={k}: {acc}')

Accuracy for k=1: 0.9666666666666667
Accuracy for k=2: 1.0
Accuracy for k=3: 1.0
Accuracy for k=4: 1.0
Accuracy for k=5: 1.0
Accuracy for k=6: 1.0
Accuracy for k=7: 1.0
Accuracy for k=8: 1.0
Accuracy for k=9: 1.0
Accuracy for k=10: 1.0
Accuracy for k=11: 1.0
Accuracy for k=12: 1.0
Accuracy for k=13: 1.0
Accuracy for k=14: 1.0
Accuracy for k=15: 1.0
Accuracy for k=16: 1.0
Accuracy for k=17: 1.0
Accuracy for k=18: 0.9666666666666667
Accuracy for k=19: 0.9666666666666667
Accuracy for k=20: 0.9666666666666667


In [13]:
best_k=k_values[np.argmax(accuracies)]
print(f"\nBest K value is: {best_k}")


Best K value is: 2


In [17]:
final_knn=KNeighborsClassifier(n_neighbors=best_k)
final_knn.fit(x_train,y_train)
y_pred=final_knn.predict(x_test)
print('confusion matrix is:')
print(confusion_matrix(y_test,y_pred))
print('accuracy score is:')
print(accuracy_score(y_test,y_pred))

confusion matrix is:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
accuracy score is:
1.0
